### PR TITLE
add perl 5.22

### PR DESCRIPTION
**Pull request by cakirke**
https://travis-ci.org/cakirke/net-ssh2/builds/123614880

too bad Travis CI supports OSX but not perl: https://github.com/travis-ci/travis-ci/issues/2314

can confirm successful local build/test on OSX 10.11.4/perl 5.22.0

### CODE REVIEW

**Comment by salva** [comment]
Thank you!

**Comment by Apollon77** [comment]
When this could become officially available?

**Comment by salva** [comment]
@Apollon77, what are you expecting to become "officially available" exactly?

**Comment by Apollon77** [comment]
I understand "can confirm successful local build/test on OSX 10.11.4/perl 5.22.0" so that with this perl version we could have perl support on MacOS environments ... or ?! Then I would be iterested in that :-)

**Comment by salva** [comment]
@Apollon77: sorry it is still not clear to me what you mean.

Do you want having a working Net::SSH2 for OSX 10.11.4/perl 5.22.0? AFAIK, there were no issues using the latest version of the module from CPAN under any combination of OS/X and Perl versions.

If you have any, open a new bug report which as much debugging information as possible, please.

**Comment by Apollon77** [comment]
Everything great ... I came to this issue over a link from travis-ci github and did not saw that this is your project, and thought it's travis-ci :-(

**Pull request merged**
