### PR TITLE
Example for SFTP File write

### PR DESCRIPTION
**Pull request by olegwtf**
I missed example for `write()` method in Net::SSH2::File. Spent some time to find how it should be used.

This example based on https://www.libssh2.org/examples/sftp_write.html and it works correct for me. I uploaded several big and small files and they have correct md5sum and size.

Btw, where should I get constants like `O_WRONLY` from? I used Fcntl for this, but thinks that they may potentially have other values in libssh2.

### CODE REVIEW

**Comment by rkitover** [comment]
Nice.

Why don't we also use this code to make a perl `$sftp->put($file_path)` method?

There is no reason for most users to deal with this, and your code is fine for this purpose.

**Comment by olegwtf** [comment]
I agree. We need `$sftp->put()`.

**Comment by salva** [comment]
> Btw, where should I get constants like O_WRONLY from? I used Fcntl for this, but thinks that they may potentially have other values in libssh2.

Actually, Net::SSH2::File::open is doing the translation between the Fcntl and the libssh2/SFTP constant values under the hood.

Using the O_* constants is the right thing to do.

**Comment by olegwtf** [comment]
> Using the O_* constants is the right thing to do.

Thanks

**Comment by rkitover** [comment]
@salva hey thought you were gone, I did a bit of minor maintenance related to mac and windows build issues, will coordinate with you through PRs.

**Comment by salva** [comment]
> I agree. We need $sftp->put().

So far, I have refrained from improving Net::SSH2 SFTP support because the SFTP (and SCP) support in libssh2 is suboptimal and full of bugs.

In order to provide a performant SFTP implementation you need to support pipelining and libssh2 devs tried to do that without exposing the pipelining process or even changing the library API. That resulted in lots of corner cases and subtle bugs.

If you follow the libssh2 mailing list, you will see that SFTP issues are reported all the time.

So, I have always discoraged using Net::SSH2::SFTP and recomended using [Net::SFTP::Foreign](https://metacpan.org/pod/Net::SFTP::Foreign) (which is a pure perl SFTP implementation) with the [Net::SSH2 backend](https://metacpan.org/pod/Net::SFTP::Foreign::Backend::Net_SSH2) instead.

**Comment by salva** [comment]
> @salva hey thought you were gone, I did a bit of minor maintenance related to mac and windows build issues, will coordinate with you through PRs.

Well, I am not gone, but it is true that I have not using Perl too much lately and the time I can put in supporting my CPAN modules is quite scarce. Also, I don't own a Mac and my Windows knowledge is limited, so most of the time I just let bugs related to those OSs pass unattended!

**Comment by rkitover** [comment]
> Well, I am not gone, but it is true that I have not using Perl too much lately and the time I can put in supporting my CPAN modules is quite scarce.

Well good to see that you're here, I hope you are well and the quarantine situation is not too onerous for you.

> So, I have always discoraged using Net::SSH2::SFTP and recomended using Net::SFTP::Foreign (which is a pure perl SFTP implementation) with the Net::SSH2 backend instead.

Should we consider then depending on Net::SFTP::Foreign and plugging it in directly as the implementation for Net::SSH2::SFTP?

**Pull request merged**
